USE PROYECTO_SQL;


/* CREATE TABLE Empresas (
    ID_EMPRESA INT PRIMARY KEY,
    NOMBRE VARCHAR(255),
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(20)
);


CREATE TABLE Proveedores (
    ID_PROVEEDOR INT PRIMARY KEY,
    NOMBRE VARCHAR(255),
    TELEFONO VARCHAR(20)
);


CREATE TABLE Productos (
    ID_PRODUCTO INT PRIMARY KEY,
    NOMBRE VARCHAR(255),
    MARCA VARCHAR(255),
    PRECIO DECIMAL(10, 2), 
    FECHA_VENCIMIENTO DATE,
    DESCRIPCION TEXT
);


CREATE TABLE Pedidos (
    ID_PEDIDO INT PRIMARY KEY,
    ID_PROVEEDOR INT,
    ID_PRODUCTO INT,
    MARCA VARCHAR(255),
    CANTIDAD INT,
    PRECIO DECIMAL(10, 2),
    FECHA_PEDIDO DATE,
    FECHA_VENCIMIENTO DATE,
    FECHA_DESPACHO DATE,
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES Proveedores(ID_PROVEEDOR),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES Productos(ID_PRODUCTO)
);



CREATE TABLE Ventas (
    ID_VENTA INT PRIMARY KEY,
    COMPRADOR VARCHAR(255),
    FECHA_COMPRA DATE,
    CANTIDAD_PRODUCTOS INT,
    PRECIO_VENTA DECIMAL(10, 2),
    N_FACTURA VARCHAR(20)
);*/ 

